name: AI Code Review

on:
  push:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AI Code Review
        uses: Codium-ai/pr-agent@main
        with:
          openai_api_key: ${{ secrets.OPENAI_KEY }}
